
width: 1280
height: 1024
Offset_x: 0
Offset_y: 0
FrameRateEnable: true
FrameRate: 50
ExposureTime: 30000
GainAuto: 1 # 0: off, 1: once, 2: Continuous
Gain: 10000.0

TriggerMode: 0
LineSelector: 0


BayerCvtQuality: 1

isColor: True

undistortion: True
alpha: 0.0 # 1: Remain all pixels with black frame. 0: Loss of pixels and no black frame.
interpolation: 1

