
width: 1280
height: 1024
Offset_x: 0
Offset_y: 0
FrameRateEnable: true
FrameRate: 50
ExposureTime: 50000
GainAuto: 0 # 0: off, 1: once, 2: Continuous
Gain: 10000.0


BayerCvtQuality: 0

isColor: True

undistortion: True
alpha: 1.0 # 1: Remain all pixels with black frame. 0: Loss of pixels and no black frame.
interpolation: 1

