
ros_image_publish_rate: 45

image_file_save_path: "/home/quintinumi/图片/img/"

camera_instrinsics_path_yaml: "/home/quintinumi/project/ws_camera_caliberation/src/camera_caliberation/src/camera_caliberation_pkg/config/caliberation_param.yaml"
